version: '3.8'

services:
  humac:
    build:
      context: .
      dockerfile: Dockerfile.ARM
    container_name: Humac_fanuc_driver
    image: humac_fanuc_image
    privileged: true

    network_mode: host
    volumes:
      - ./lib:/humac/lib
      - ./fanuc:/humac/fanuc
      - ./pyfocas:/humac/pyfocas
      - ./FanucImplementation:/humac/FanucImplementation